### ISSUE TITLE
Command (or control) click on blue `Boek` button not working

### ISSUE THREAD

**Issue by remcotolsma** [pronamic/basecone#3]
I use `command` (`⌘`) (on Windows `ctrl`) + click a lot to open webpages in a new web browser tab. If i  `command` (`⌘`) + `click` on the blue `Boek` button the document to book is not opened.

<img width="402" alt="Schermafbeelding 2022-07-06 om 14 16 53" src="https://user-images.githubusercontent.com/869674/177548876-e2c3c5a0-1e92-45f7-8658-a01bf0281d18.png">

<img width="1987" alt="Schermafbeelding 2022-07-06 om 14 18 21" src="https://user-images.githubusercontent.com/869674/177548915-3f89aa2b-96b9-4e6c-aca3-d2edcf2f3ce2.png">

That is very inconvenient and in a modern web application you can expect this to work just fine in my opinion.

I also assume that the console error messages are not intended.

```
Uncaught TypeError: Cannot read properties of null (reading 'access_token')
    at HTMLDocument.<anonymous> (Booking?DocumentId=4a964781-1769-44ea-bcaa-81efecfcfc97&CompanyId=2ed4c8ee-3748-48c7-8e54-cf0d9374da25&From=DocumentsList:532:74)
    at h (vendor.min-e8ec70d6.js:16:9166)
    at Object.fireWith (vendor.min-e8ec70d6.js:16:9930)
    at Function.ready (vendor.min-e8ec70d6.js:16:3962)
    at HTMLDocument.a (vendor.min-e8ec70d6.js:16:8637)
    at HTMLDocument.nrWrapper (Booking?DocumentId=4a964781-1769-44ea-bcaa-81efecfcfc97&CompanyId=2ed4c8ee-3748-48c7-8e54-cf0d9374da25&From=DocumentsList:13:30230)
Booking?DocumentId=4a964781-1769-44ea-bcaa-81efecfcfc97&CompanyId=2ed4c8ee-3748-48c7-8e54-cf0d9374da25&From=DocumentsList:13 Uncaught TypeError: Cannot read properties of null (reading 'access_token')
    at initializeComments (Booking?DocumentId=4a964781-1769-44ea-bcaa-81efecfcfc97&CompanyId=2ed4c8ee-3748-48c7-8e54-cf0d9374da25&From=DocumentsList:392:78)
    at Booking?DocumentId=4a964781-1769-44ea-bcaa-81efecfcfc97&CompanyId=2ed4c8ee-3748-48c7-8e54-cf0d9374da25&From=DocumentsList:440:17
    at nrWrapper (Booking?DocumentId=4a964781-1769-44ea-bcaa-81efecfcfc97&CompanyId=2ed4c8ee-3748-48c7-8e54-cf0d9374da25&From=DocumentsList:13:30230)
```

**Comment by remcotolsma** [comment]
Sent via https://www.wolterskluwer.com/nl-nl/solutions/basecone/contact:

> Beste lezer,
> 
> Command + click op blauw "Boek" button werkt niet, zie:
> https://github.com/pronamic/basecone/issues/3
> 
> Met vriendelijke groet,
> 
> Remco Tolsma
> Pronamic

Awaiting response.

<img width="831" alt="Schermafbeelding 2022-07-06 om 14 24 49" src="https://user-images.githubusercontent.com/869674/177549601-b722d634-1d35-4a98-8d1e-f883886a344d.png">

**Comment by remcotolsma** [comment]
**Rosa** from **Basecone** replied on **Wed, 06 Jul 2022 15:41:49 +0000**:

> Goedemiddag Remco,
> 
> Kan je dit als schermopname aan mij laten zien? Zodat ik dit kan delen met desbetreffend team?
> 
> Bij voorbaat dank.
> 
> Met vriendelijke groeten,
> 
> Rosa

**Comment by remcotolsma** [comment]
https://user-images.githubusercontent.com/869674/177719211-45a63301-49d6-4880-84e0-30df5ead40be.mov

**Comment by remcotolsma** [comment]
> Hoi Rosa,
> 
> Heb je al wel geprobeerd wat ik heb omschreven? Volgens mij is het probleem namelijk vrij eenvoudig te reproduceren. Wat dat betreft zou een schermopname niet eens nodig hoeven te zijn. Om de vaart er in te houden heb ik maar even voor de volledigheid een schermopname gemaakt. Zie hiervoor: https://github.com/pronamic/basecone/issues/3#issuecomment-1177204335. Je ziet na 6 seconden dat het nieuw geopende tabblad niet het document toont wat ik wil boeken. Let ook op dat ik dus met command toets (⌘) (in Windows ctrl) klik op de blauwe "Boek" knop.
> 
> Met vriendelijke groet,
> 
> Remco Tolsma
